let myMenu = "";
myMenu += '<a href="index.html" class="d-flex align-items-center py-3 mb-3 link-dark text-decoration-none border-bottom">';
myMenu += '<img width="35px" style="margin-left: 14px" src="img/icons/laravel.svg" />';
myMenu += '<img width="35px" style="margin-left: 10px" src="img/icons/vue.svg" />';
myMenu += '<img width="35px" style="margin-left: 10px" src="img/icons/bootstrap.svg" />';
myMenu += '<img width="35px" style="margin-left: 10px" src="img/icons/visual-studio-code.svg" />';
myMenu += '<img width="35px" style="margin-left: 10px" src="img/icons/sass.svg" />';
myMenu += '</a>';

myMenu += '<ul class="list-unstyled ps-0">';
myMenu += '<li class="mb-1">';
myMenu += '<button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse" data-bs-target="#home-collapse" aria-expanded="true"> Comandos </button>';
myMenu += '<div class="collapse" id="home-collapse">';
myMenu += '<ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">';
myMenu += '<li><a href="index.html#laravel" class="link-dark rounded">Comandos Laravel</a></li>';
myMenu += '<li><a href="index.html#vue" class="link-dark rounded">Comandos Vue</a></li>';
myMenu += '<li><a href="index.html#vsc" class="link-dark rounded">Atajos Visual Studio Code</a></li>';
myMenu += '<li><a href="index.html#git" class="link-dark rounded">Comandos Git</a></li>';
myMenu += '<li>';
myMenu += '<a href="https://sass-lang.com/guide" class="link-dark rounded" target="_blank">Comandos Sass Css <i class="bx bx-exit"></i></a>';
myMenu += '</li>';
myMenu += '<li>';
myMenu += '<a href="https://bluuweb.github.io/desarrollo-web-bluuweb/07-01-git/#enlaces" class="link-dark rounded" target="_blank">Comandos Git Bluuweb <i class="bx bx-exit"></i></a>';
myMenu += '</li>';
myMenu += '<li>';
myMenu += '<a href="https://bluuweb.github.io/desarrollo-web-bluuweb/07-00-terminal/" class="link-dark rounded" target="_blank" >Comandos CMD Bluuweb <i class="bx bx-exit"></i ></a>';
myMenu += '</li>';
myMenu += '</ul>';
myMenu += '</div>';
myMenu += '</li>';
myMenu += '<li class="mb-1">';
myMenu += '<button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse" data-bs-target="#css-collapse" aria-expanded="false">Css</button>';
myMenu += '<div class="collapse" id="css-collapse">';
myMenu += '<ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">';
myMenu += '<li><a href="css.html#css" class="link-dark rounded">Clases genericas</a></li>';
myMenu += '<li>';
myMenu += '<a href="css.html#clases" class="link-dark rounded">Descargar clases <i class="bx bxs-download"></i></a>';
myMenu += '</li>';
myMenu += '<li><a href="css.html#tabla" class="link-dark rounded">Tabla</a></li>';
myMenu += '<li><a href="css.html#fantasma" class="link-dark rounded">Boton fantasma</a></li>';
myMenu += '<li><a href="css.html#link" class="link-dark rounded">Boton Link</a></li>';
myMenu += '<li><a href="css.html#paginador" class="link-dark rounded">Boton paginador</a></li>';
myMenu += '<li><a href="css.html#file" class="link-dark rounded">Boton File</a></li>';
myMenu += '<li>';
myMenu += '<a href="http://www.menucool.com/tooltip/css-tooltip" target="_blank" class="link-dark rounded">Tooltips <i class="bx bx-exit"></i></a>';
myMenu += '</li>';
myMenu += '<li>';
myMenu += '<a href="https://www.w3schools.com/css/default.asp" target="_blank" class="link-dark rounded">W3schools <i class="bx bx-exit"></i></a>';
myMenu += '</li>';
myMenu += '</ul>';
myMenu += '</div>';
myMenu += '</li>';

myMenu += '<li class="mb-1">';
myMenu += '<button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse" data-bs-target="#js-collapse" aria-expanded="false">JavaScript</button>';
myMenu += '<div class="collapse" id="js-collapse">';
myMenu += '<ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">';
myMenu += '<li><a href="javascript.html#qjs" class="link-dark rounded">¿Que es JavaScript?</a></li>';
myMenu += '<li><a href="javascript.html#qhjs" class="link-dark rounded">¿Qué hace JavaScript?</a></li>';

myMenu += '<li><a href="javascript.html#historia" class="link-dark rounded">Historia</a></li>';
myMenu += '<li><a href="javascript.html#variables" class="link-dark rounded">Tipos de variables</a></li>';

myMenu += '<li><a href="javascript.html#tdatos" class="link-dark rounded">Tipos de datos</a></li>';
myMenu += '<li><a href="javascript.html#ologicos" class="link-dark rounded">Operadores lógicos</a></li>';
myMenu += '<li><a href="javascript.html#obasicas" class="link-dark rounded">Operaciones Basicas</a></li>';
myMenu += '<li><a href="javascript.html#expresiones" class="link-dark rounded">Expresiónes</a></li>';
myMenu += '<li><a href="javascript.html#funciones" class="link-dark rounded">Funciones</a></li>';
myMenu += '<li><a href="javascript.html#case" class="link-dark rounded">Switch Case</a></li>';
myMenu += '<li><a href="javascript.html#prompt" class="link-dark rounded">Prompt</a></li>';
myMenu += '<li><a href="javascript.html#dom" class="link-dark rounded">DOM</a></li>';
myMenu += '<li><a href="javascript.html#dom" class="link-dark rounded">Fechas e Interpolaciones</a></li>';
myMenu += '<li><a href="javascript.html#for" class="link-dark rounded">Bucle For</a></li>';
myMenu += '<li><a href="javascript.html#foreach" class="link-dark rounded">Bucle ForEach</a></li>';
myMenu += '<li><a href="javascript.html#while" class="link-dark rounded">Bucle While</a></li>';
myMenu += '</ul>';
myMenu += '</div>';
myMenu += '</li>';

myMenu += '<li class="mb-1">';
myMenu += '<button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse" data-bs-target="#poo-collapse" aria-expanded="false">POO</button>';
myMenu += '<div class="collapse" id="poo-collapse">';
myMenu += '<ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">';
myMenu += '<li><a href="poo.html#poo" class="link-dark rounded">¿Qué es POO?</a></li>';
myMenu += '<li><a href="poo.html#definiciones" class="link-dark rounded">Algunas definiciones</a></li>';

myMenu += '<li><a href="poo.html#beneficios" class="link-dark rounded">Beneficios de POO</a></li>';
myMenu += '<li><a href="poo.html#modularidad" class="link-dark rounded">¿Qué es modularidad?</a></li>';

myMenu += '<li><a href="poo.html#instancia" class="link-dark rounded">¿Qué es una instancia?</a></li>';
myMenu += '<li><a href="poo.html#clase" class="link-dark rounded">¿Qué es una clase?</a></li>';
myMenu += '<li><a href="poo.html#objeto" class="link-dark rounded">¿Qué es un objeto?</a></li>';
myMenu += '<li><a href="poo.html#atributo" class="link-dark rounded">¿Qué es un atributo?</a></li>';
myMenu += '<li><a href="poo.html#metodo" class="link-dark rounded">¿Qué es un método?</a></li>';
myMenu += '<li><a href="poo.html#case" class="link-dark rounded">¿Qué es encapsulación?</a></li>';
myMenu += '<li><a href="poo.html#abstraccion" class="link-dark rounded">¿Qué es abstracción?</a></li>';
myMenu += '<li><a href="poo.html#herencia" class="link-dark rounded">¿Qué es herencia?</a></li>';
myMenu += '<li><a href="poo.html#polimorfismo" class="link-dark rounded">¿Qué es polimorfismo?</a></li>';
myMenu += '</ul>';
myMenu += '</div>';
myMenu += '</ >';

myMenu += '<li class="mb-1">';
myMenu += '<button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse" data-bs-target="#instal-collapse" aria-expanded="false">Instaladores</button>';
myMenu += '<div class="collapse" id="instal-collapse">';
myMenu += '<ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">';
myMenu += '<li><a href="instaladores.html#instaladores" class="link-dark rounded">Xampp</a></li>';
myMenu += '<li><a href="instaladores.html#vue2" class="link-dark rounded">Vuejs</a></li>';
myMenu += '<li><a href="instaladores.html#laravel2" class="link-dark rounded">Laravel y Composer</a></li>';
myMenu += '<li><a href="instaladores.html#vscode" class="link-dark rounded">Configuración VSC</a></li>';
myMenu += '<li><a href="https://rubyinstaller.org/downloads/" class="link-dark rounded" target="_blank">Ruby Instaler para Sass Css <i class="bx bx-exit"></i></a></li>';
myMenu += '</ul>';
myMenu += '</div>';
myMenu += '</li>';

myMenu += '<li class="border-top my-3"></li>';

myMenu += '<li class="mb-1">';
myMenu += '<button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse" data-bs-target="#scrum-collapse" aria-expanded="false">Metodologia Scrum</button>';
myMenu += '<div class="collapse" id="scrum-collapse">';
myMenu += '<ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">';
myMenu += '<li><a href="scrum.html#qscrum" class="link-dark rounded">¿Qué es Scrum?</a></li>';
myMenu += '<li><a href="scrum.html#pqscrum" class="link-dark rounded">¿Por qué Scrum?</a></li>';
myMenu += '<li><a href="scrum.html#pilares" class="link-dark rounded">Pilares del Scrum</a></li>';
myMenu += '<li><a href="scrum.html#roles" class="link-dark rounded">Roles</a></li>';
myMenu += '<li><a href="scrum.html#owner" class="link-dark rounded"><i class="bx bx-chevron-right"></i> Rol Product owner</a></li>';
myMenu += '<li><a href="scrum.html#master" class="link-dark rounded"><i class="bx bx-chevron-right"></i> Rol Scrum Master</a></li>';
myMenu += '<li><a href="scrum.html#equipo" class="link-dark rounded"><i class="bx bx-chevron-right"></i> Rol Equipo de desarrollo</a></li>';
myMenu += '<li><a href="scrum.html#sprint" class="link-dark rounded">Sprint</a></li>';
myMenu += '<li><a href="scrum.html#planning" class="link-dark rounded">Sprint planning</a></li>';
myMenu += '<li><a href="scrum.html#pbacklog" class="link-dark rounded">Product Backlog</a></li>';
myMenu += '<li><a href="scrum.html#sbacklog" class="link-dark rounded">Sprint Backlog</a></li>';
myMenu += '<li><a href="scrum.html#daily" class="link-dark rounded">Daily meeting</a></li>';
myMenu += '<li><a href="scrum.html#sreview" class="link-dark rounded">Sprint review</a></li>';
myMenu += '<li><a href="scrum.html#sretros" class="link-dark rounded">Sprint retrospective</a></li>';
myMenu += '<li><a href="scrum.html#ventajas" class="link-dark rounded">Ventajas</a></li>';
myMenu += '<li><a href="scrum.html#desventajas" class="link-dark rounded">Desventajas</a></li>';
myMenu += '</ul>';
myMenu += '</div>';
myMenu += '</li>';

myMenu += '<li class="border-top my-3"></li>';

myMenu += '<li class="mb-1">';
myMenu += '<button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse" data-bs-target="#drive-collapse" aria-expanded="false">Material de apoyo</button>';
myMenu += '<div class="collapse" id="drive-collapse">';
myMenu += '<ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">';
myMenu += '<li><a href="material_de_apoyo.html#tutoriales" class="link-dark rounded">Tutoriales</a></li>';
myMenu += '<li><a href="material_de_apoyo.html#marcadores" class="link-dark rounded">Marcadores</a></li>';
myMenu += '<li><a href="https://drive.google.com/drive/folders/0B1R6zq7kCgNAcW03ajhCQUpnSmM?resourcekey=0-gs5HhVQFzYaZKYItQBcmlg&usp=sharing" target="_blank" class="link-dark rounded">Plantillas Drive <i class="bx bx-exit"></i></a></li>';
myMenu += '<li><a href="https://drive.google.com/drive/folders/1NTtfJJFlc6S6LFbxwE94ay2JyafMUkeG?usp=sharing" target="_blank" class="link-dark rounded">Programas Drive <i class="bx bx-exit"></i></a></li>';
myMenu += '<li><a href="https://drive.google.com/drive/folders/0B1R6zq7kCgNAQU5PUUV0R2hrVDg?resourcekey=0-lB6JlQEoZtPX8F8yy6Ov3g&usp=sharing" target="_blank" class="link-dark rounded">Corel Draw Drive <i class="bx bx-exit"></i></a></li>';
myMenu += '</ul>';
myMenu += '</div>';
myMenu += '</li>';

myMenu += '<li class="border-top my-3"></li>';

myMenu += '<li class="mb-1">';
myMenu += '<button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse" data-bs-target="#github-collapse"naria-expanded="false">Github Pages</button>';
myMenu += '<div class="collapse" id="github-collapse">';
myMenu += '<ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">';
myMenu += '<li><a href="https://bigjack2.github.io/pruebaboostrap5.github.io/" target="_blank" class="link-dark rounded">Demo Bootstrap 5 <i class="bx bx-exit"></i></a></li>';
myMenu += '<li><a href="https://bigjack2.github.io/portafolio_vanegas.github.io/" target="_blank" class="link-dark rounded">Portafolio web <i class="bx bx-exit"></i></a></li>';
myMenu += '</ul>';
myMenu += '</div>';
myMenu += '</li>';
myMenu += '</ul >';

document.getElementById("jsMenu").innerHTML = myMenu;