let myMenu = "";
myMenu += '<a href="index.html" class="d-flex align-items-center py-3 mb-3 link-dark text-decoration-none border-bottom">';
myMenu += '<img width="35px" style="margin-left: 14px" src="img/icons/laravel.svg" />';
myMenu += '<img width="35px" style="margin-left: 10px" src="img/icons/vue.svg" />';
myMenu += '<img width="35px" style="margin-left: 10px" src="img/icons/bootstrap.svg" />';
myMenu += '<img width="35px" style="margin-left: 10px" src="img/icons/visual-studio-code.svg" />';
myMenu += '<img width="35px" style="margin-left: 10px" src="img/icons/sass.svg" />';
myMenu += '</a>';

myMenu += '<ul class="list-unstyled ps-0">';
myMenu += '<li class="mb-1">';
myMenu += '<button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse" data-bs-target="#home-collapse" aria-expanded="true"> Comandos </button>';
myMenu += '<div class="collapse" id="home-collapse">';
myMenu += '<ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">';
myMenu += '<li><a href="index.html#laravel" class="link-dark rounded">Comandos Laravel</a></li>';
myMenu += '<li><a href="index.html#vue" class="link-dark rounded">Comandos Vue</a></li>';
myMenu += '<li><a href="index.html#vsc" class="link-dark rounded">Atajos Visual Studio Code</a></li>';
myMenu += '<li><a href="index.html#git" class="link-dark rounded">Comandos Git</a></li>';
myMenu += '<li>';
myMenu += '<a href="https://sass-lang.com/guide" class="link-dark rounded" target="_blank">Comandos Sass Css <i class="bx bx-exit"></i></a>';
myMenu += '</li>';
myMenu += '<li>';
myMenu += '<a href="https://bluuweb.github.io/desarrollo-web-bluuweb/07-01-git/#enlaces" class="link-dark rounded" target="_blank">Comandos Git Bluuweb <i class="bx bx-exit"></i></a>';
myMenu += '</li>';
myMenu += '<li>';
myMenu += '<a href="https://bluuweb.github.io/desarrollo-web-bluuweb/07-00-terminal/" class="link-dark rounded" target="_blank" >Comandos CMD Bluuweb <i class="bx bx-exit"></i ></a>';
myMenu += '</li>';
myMenu += '</ul>';
myMenu += '</div>';
myMenu += '</li>';
myMenu += '<li class="mb-1">';
myMenu += '<button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse" data-bs-target="#css-collapse" aria-expanded="false">Css</button>';
myMenu += '<div class="collapse" id="css-collapse">';
myMenu += '<ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">';
myMenu += '<li><a href="css.html#css" class="link-dark rounded">Clases genericas</a></li>';
myMenu += '<li>';
myMenu += '<a href="css.html#clases" class="link-dark rounded">Descargar clases <i class="bx bxs-download"></i></a>';
myMenu += '</li>';
myMenu += '<li><a href="css.html#tabla" class="link-dark rounded">Tabla</a></li>';
myMenu += '<li><a href="css.html#fantasma" class="link-dark rounded">Boton fantasma</a></li>';
myMenu += '<li><a href="css.html#link" class="link-dark rounded">Boton Link</a></li>';
myMenu += '<li><a href="css.html#paginador" class="link-dark rounded">Boton paginador</a></li>';
myMenu += '<li><a href="css.html#file" class="link-dark rounded">Boton File</a></li>';
myMenu += '<li>';
myMenu += '<a href="http://www.menucool.com/tooltip/css-tooltip" target="_blank" class="link-dark rounded">Tooltips <i class="bx bx-exit"></i></a>';
myMenu += '</li>';
myMenu += '<li>';
myMenu += '<a href="https://www.w3schools.com/css/default.asp" target="_blank" class="link-dark rounded">W3schools <i class="bx bx-exit"></i></a>';
myMenu += '</li>';
myMenu += '</ul>';
myMenu += '</div>';
myMenu += '</li>';

myMenu += '<li class="mb-1">';
myMenu += '<button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse" data-bs-target="#js-collapse" aria-expanded="false">JavaScript</button>';
myMenu += '<div class="collapse" id="js-collapse">';
myMenu += '<ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">';
myMenu += '<li><a href="javascript.html#qjs" class="link-dark rounded">¿Que es JavaScript?</a></li>';
myMenu += '<li><a href="javascript.html#qhjs" class="link-dark rounded">¿Qué hace JavaScript?</a></li>';

myMenu += '<li><a href="javascript.html#historia" class="link-dark rounded">Historia</a></li>';
myMenu += '<li><a href="javascript.html#variables" class="link-dark rounded">Tipos de variables</a></li>';

myMenu += '<li><a href="javascript.html#tdatos" class="link-dark rounded">Tipos de datos</a></li>';
myMenu += '<li><a href="javascript.html#ologicos" class="link-dark rounded">Operadores lógicos</a></li>';
myMenu += '<li><a href="javascript.html#obasicas" class="link-dark rounded">Operaciones Basicas</a></li>';
myMenu += '<li><a href="javascript.html#expresiones" class="link-dark rounded">Expresiónes</a></li>';
myMenu += '<li><a href="javascript.html#funciones" class="link-dark rounded">Funciones</a></li>';
myMenu += '<li><a href="javascript.html#case" class="link-dark rounded">Switch Case</a></li>';
myMenu += '<li><a href="javascript.html#prompt" class="link-dark rounded">Prompt</a></li>';
myMenu += '<li><a href="javascript.html#dom" class="link-dark rounded">DOM</a></li>';
myMenu += '<li><a href="javascript.html#dom" class="link-dark rounded">Fechas e Interpolaciones</a></li>';
myMenu += '<li><a href="javascript.html#for" class="link-dark rounded">Bucle For</a></li>';
myMenu += '<li><a href="javascript.html#foreach" class="link-dark rounded">Bucle ForEach</a></li>';
myMenu += '<li><a href="javascript.html#while" class="link-dark rounded">Bucle While</a></li>';
myMenu += '</ul>';
myMenu += '</div>';
myMenu += '</li>';

myMenu += '<li class="mb-1">';
myMenu += '<button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse" data-bs-target="#poo-collapse" aria-expanded="false">POO</button>';
myMenu += '<div class="collapse" id="poo-collapse">';
myMenu += '<ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">';
myMenu += '<li><a href="poo.html#poo" class="link-dark rounded">¿Qué es POO?</a></li>';
myMenu += '<li><a href="poo.html#definiciones" class="link-dark rounded">Algunas definiciones</a></li>';

myMenu += '<li><a href="poo.html#beneficios" class="link-dark rounded">Beneficios de POO</a></li>';
myMenu += '<li><a href="poo.html#modularidad" class="link-dark rounded">¿Qué es modularidad?</a></li>';

myMenu += '<li><a href="poo.html#instancia" class="link-dark rounded">¿Qué es una instancia?</a></li>';
myMenu += '<li><a href="poo.html#clase" class="link-dark rounded">¿Qué es una clase?</a></li>';
myMenu += '<li><a href="poo.html#objeto" class="link-dark rounded">¿Qué es un objeto?</a></li>';
myMenu += '<li><a href="poo.html#atributo" class="link-dark rounded">¿Qué es un atributo?</a></li>';
myMenu += '<li><a href="poo.html#metodo" class="link-dark rounded">¿Qué es un método?</a></li>';
myMenu += '<li><a href="poo.html#case" class="link-dark rounded">¿Qué es encapsulación?</a></li>';
myMenu += '<li><a href="poo.html#abstraccion" class="link-dark rounded">¿Qué es abstracción?</a></li>';
myMenu += '<li><a href="poo.html#herencia" class="link-dark rounded">¿Qué es herencia?</a></li>';
myMenu += '<li><a href="poo.html#polimorfismo" class="link-dark rounded">¿Qué es polimorfismo?</a></li>';
myMenu += '</ul>';
myMenu += '</div>';
myMenu += '</ >';

myMenu += '<li class="mb-1">';
myMenu += '<button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse" data-bs-target="#git-collapse" aria-expanded="false">Desarrollo basado en Git</button>';
myMenu += '<div class="collapse" id="git-collapse">';
myMenu += '<ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">';
myMenu += '<li><a href="git-flow.html#que-es-git" class="link-dark rounded">¿Que es Git?</a></li>';
myMenu += '<li><a href="git-flow.html#control-versiones" class="link-dark rounded">¿Qué es un control de versiones?</a></li>';
myMenu += '<li><a href="git-flow.html#repositorio" class="link-dark rounded">Repositorio</a></li>';
myMenu += '<li><a href="git-flow.html#barnch" class="link-dark rounded">Branch (ramificaciones)</a></li>';
myMenu += '<li><a href="git-flow.html#pull" class="link-dark rounded">Pull Request (Fusión)</a></li>';
myMenu += '<li><a href="git-flow.html#tag" class="link-dark rounded">Tag</a></li>';
myMenu += '<li><a href="git-flow.html#fork" class="link-dark rounded">Fork</a></li>';
myMenu += '<li><a href="git-flow.html#cuando-usar-git" class="link-dark rounded">Cuándo usar Github</a></li>';
myMenu += '<li><a href="git-flow.html#git-flow" class="link-dark rounded">Git-Flow</a></li>';
myMenu += '<li><a href="git-flow.html#github" class="link-dark rounded">GitHub-Flow</a></li>';
myMenu += '<li><a href="git-flow.html#gitlab" class="link-dark rounded">Gitlab-Flow</a></li>';
myMenu += '<li><a href="git-flow.html#trunk" class="link-dark rounded">Trunk Based Development</a></li>';
myMenu += '</ul>';
myMenu += '</div>';
myMenu += '</li>';

myMenu += '<li class="mb-1">';
myMenu += '<button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse" data-bs-target="#instal-collapse" aria-expanded="false">Instaladores</button>';
myMenu += '<div class="collapse" id="instal-collapse">';
myMenu += '<ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">';
myMenu += '<li><a href="instaladores.html#instaladores" class="link-dark rounded">Xampp</a></li>';
myMenu += '<li><a href="instaladores.html#vue2" class="link-dark rounded">Vuejs</a></li>';
myMenu += '<li><a href="instaladores.html#laravel2" class="link-dark rounded">Laravel y Composer</a></li>';
myMenu += '<li><a href="instaladores.html#vscode" class="link-dark rounded">Configuración VSC</a></li>';
myMenu += '<li><a href="https://rubyinstaller.org/downloads/" class="link-dark rounded" target="_blank">Ruby Instaler para Sass Css <i class="bx bx-exit"></i></a></li>';
myMenu += '</ul>';
myMenu += '</div>';
myMenu += '</li>';

myMenu += '<li class="mb-1">';
myMenu += '<button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse" data-bs-target="#diccionario-collapse" aria-expanded="false">Diccionario</button>';
myMenu += '<div class="collapse" id="diccionario-collapse">';
myMenu += '<ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">';
myMenu += '<li><a href="diccionario.html#camel" class="link-dark rounded">CamelCase</a></li>';
myMenu += '<li><a href="diccionario.html#pascal" class="link-dark rounded">PascalCase</a></li>';
myMenu += '<li><a href="diccionario.html#snake" class="link-dark rounded">SnakeCase</a></li>';
myMenu += '<li><a href="diccionario.html#castear" class="link-dark rounded">¿Qué es castear una variable?</a></li>';
myMenu += '<li><a href="diccionario.html#instancia" class="link-dark rounded">¿Qué es una instancia?</a></li>';
myMenu += '<li><a href="diccionario.html#asincronismo" class="link-dark rounded">Qué es asincronismo?</a></li>';
myMenu += '<li><a href="diccionario.html#paralelismo" class="link-dark rounded">¿Qué es una paralelismo?</a></li>';
myMenu += '<li><a href="diccionario.html#sincronismo" class="link-dark rounded">¿Qué es sincronismo?</a></li>';
myMenu += '<li><a href="diccionario.html#iterar" class="link-dark rounded">¿Qué es iteración ó iterar?</a></li>';
myMenu += '<li><a href="diccionario.html#setear" class="link-dark rounded">¿Qué significa setear?</a></li>';
myMenu += '<li><a href="diccionario.html#constante" class="link-dark rounded">¿Qué es una variable constante?</a></li>';
myMenu += '<li><a href="diccionario.html#MVC" class="link-dark rounded">¿Qué es MVC?</a></li>';
myMenu += '<li><a href="diccionario.html#Modelos" class="link-dark rounded">Modelos</a></li>';
myMenu += '<li><a href="diccionario.html#Vistas" class="link-dark rounded">Vistas</a></li>';
myMenu += '<li><a href="diccionario.html#Controladores" class="link-dark rounded">Controladores</a></li>';
myMenu += '<li><a href="diccionario.html#parametro" class="link-dark rounded">¿Qué es un parametro?</a></li>';
myMenu += '<li><a href="diccionario.html#argumento" class="link-dark rounded">¿Qué es un argumento?</a></li>';
myMenu += '</ul>';
myMenu += '</div>';
myMenu += '</li>';

myMenu += '<li class="border-top my-3"></li>';

myMenu += '<li class="mb-1">';
myMenu += '<button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse" data-bs-target="#csharp-collapse" aria-expanded="false">C#</button>';
myMenu += '<div class="collapse" id="csharp-collapse">';
myMenu += '<ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">';
myMenu += '<li><a href="csharp.html#csharp" class="link-dark rounded">¿Qué es C#?</a></li>';
myMenu += '<li><a href="csharp.html#asp" class="link-dark rounded">¿Qué es ASP.Net?</a></li>';
myMenu += '<li><a href="csharp.html#variables" class="link-dark rounded">Tipos de variables</a></li>';
myMenu += '<li><a href="csharp.html#strings" class="link-dark rounded">Manejo de strings</a></li>';
myMenu += '<li><a href="csharp.html#metodos" class="link-dark rounded">Métodos en C #</a></li>';
myMenu += '<li><a href="csharp.html#parametros" class="link-dark rounded">Métodos con parametros</a></li>';
myMenu += '<li><a href="csharp.html#Arreglos" class="link-dark rounded">Arreglos</a></li>';
myMenu += '</ul>';
myMenu += '</div>';
myMenu += '</li>';

myMenu += '<li class="mb-1">';
myMenu += '<button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse" data-bs-target="#linq-collapse" aria-expanded="false">LinQ</button>';
myMenu += '<div class="collapse" id="linq-collapse">';
myMenu += '<ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">';
myMenu += '<li><a href="linq.html#linq" class="link-dark rounded">¿Qué es LinQ?</a></li>';
myMenu += '<li><a href="linq.html#ejemplo" class="link-dark rounded">Ejemplo basico de LinQ</a></li>';
myMenu += '<li><a href="linq.html#bocetos" class="link-dark rounded">LinQ explicado con bocetos</a></li>';
myMenu += '<li><a href="linq.html#select" class="link-dark rounded">Select</a></li>';
myMenu += '<li><a href="linq.html#where" class="link-dark rounded">Where</a></li>';
myMenu += '<li><a href="linq.html#many" class="link-dark rounded">SelectMany</a></li>';
myMenu += '<li><a href="linq.html#zip" class="link-dark rounded">Zip</a></li>';
myMenu += '<li><a href="linq.html#order" class="link-dark rounded">OrderBy</a></li>';
myMenu += '<li><a href="linq.html#distinct" class="link-dark rounded">Distinct</a></li>';
myMenu += '<li><a href="linq.html#aggregate" class="link-dark rounded">Aggregate</a></li>';
myMenu += '<li><a href="linq.html#chunk" class="link-dark rounded">Chunk</a></li>';
myMenu += '<li><a href="linq.html#union" class="link-dark rounded">Union</a></li>';
myMenu += '<li><a href="linq.html#intersect" class="link-dark rounded">Intersect</a></li>';
myMenu += '<li><a href="linq.html#any" class="link-dark rounded">Any</a></li>';
myMenu += '<li><a href="linq.html#all" class="link-dark rounded">All</a></li>';
myMenu += '<li><a href="linq.html#append" class="link-dark rounded">Append</a></li>';
myMenu += '<li><a href="linq.html#prepend" class="link-dark rounded">Prepend</a></li>';
myMenu += '<li><a href="linq.html#max" class="link-dark rounded">MaxBy</a></li>';
myMenu += '<li><a href="linq.html#distinctby" class="link-dark rounded">DistinctBy</a></li>';
myMenu += '<li><a href="linq.html#tolook" class="link-dark rounded">ToLookup</a></li>';
myMenu += '<li><a href="linq.html#dictionary" class="link-dark rounded">ToDictionary</a></li>';
myMenu += '<li><a href="linq.html#join" class="link-dark rounded">Join</a></li>';
myMenu += '<li><a href="linq.html#take" class="link-dark rounded">Take</a></li>';
myMenu += '<li><a href="linq.html#skip" class="link-dark rounded">Skip</a></li>';
myMenu += '<li><a href="linq.html#oftype" class="link-dark rounded">OfType</a></li>';
myMenu += '<li><a href="linq.html#group" class="link-dark rounded">GroupBy</a></li>';
myMenu += '<li><a href="linq.html#reverse" class="link-dark rounded">Reverse</a></li>';
myMenu += '<li><a href="linq.html#first" class="link-dark rounded">First()</a></li>';
myMenu += '<li><a href="linq.html#single" class="link-dark rounded">Single()</a></li>';
myMenu += '<li><a href="linq.html#firstsingle" class="link-dark rounded">FirstOrDefault / SingleOrDefault</a></li>';
myMenu += '</ul>';
myMenu += '</div>';
myMenu += '</li>';

myMenu += '<li class="mb-1">';
myMenu += '<button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse" data-bs-target="#entity-collapse" aria-expanded="false">SQL Server (Ejercicio)</button>';
myMenu += '<div class="collapse" id="entity-collapse">';
myMenu += '<ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">';
myMenu += '<li><a href="sqlserver-create.html" class="link-dark rounded">Creación de BD y tablas</a></li>';
myMenu += '<li><a href="sqlserver-insert.html" class="link-dark rounded">Inserción de datos</a></li>';
myMenu += '<li><a href="sqlserver-query.html" class="link-dark rounded">Consultas</a></li>';
myMenu += '</ul>';
myMenu += '</div>';
myMenu += '</li>';

myMenu += '<li class="border-top my-3"></li>';

myMenu += '<li class="mb-1">';
myMenu += '<button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse" data-bs-target="#scrum-collapse" aria-expanded="false">Metodologia Scrum</button>';
myMenu += '<div class="collapse" id="scrum-collapse">';
myMenu += '<ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">';
myMenu += '<li><a href="scrum.html#qscrum" class="link-dark rounded">¿Qué es Scrum?</a></li>';
myMenu += '<li><a href="scrum.html#pqscrum" class="link-dark rounded">¿Por qué Scrum?</a></li>';
myMenu += '<li><a href="scrum.html#pilares" class="link-dark rounded">Pilares del Scrum</a></li>';
myMenu += '<li><a href="scrum.html#roles" class="link-dark rounded">Roles</a></li>';
myMenu += '<li><a href="scrum.html#owner" class="link-dark rounded"><i class="bx bx-chevron-right"></i> Rol Product owner</a></li>';
myMenu += '<li><a href="scrum.html#master" class="link-dark rounded"><i class="bx bx-chevron-right"></i> Rol Scrum Master</a></li>';
myMenu += '<li><a href="scrum.html#equipo" class="link-dark rounded"><i class="bx bx-chevron-right"></i> Rol Equipo de desarrollo</a></li>';
myMenu += '<li><a href="scrum.html#sprint" class="link-dark rounded">Sprint</a></li>';
myMenu += '<li><a href="scrum.html#planning" class="link-dark rounded">Sprint planning</a></li>';
myMenu += '<li><a href="scrum.html#pbacklog" class="link-dark rounded">Product Backlog</a></li>';
myMenu += '<li><a href="scrum.html#sbacklog" class="link-dark rounded">Sprint Backlog</a></li>';
myMenu += '<li><a href="scrum.html#daily" class="link-dark rounded">Daily meeting</a></li>';
myMenu += '<li><a href="scrum.html#sreview" class="link-dark rounded">Sprint review</a></li>';
myMenu += '<li><a href="scrum.html#sretros" class="link-dark rounded">Sprint retrospective</a></li>';
myMenu += '<li><a href="scrum.html#ventajas" class="link-dark rounded">Ventajas</a></li>';
myMenu += '<li><a href="scrum.html#desventajas" class="link-dark rounded">Desventajas</a></li>';
myMenu += '</ul>';
myMenu += '</div>';
myMenu += '</li>';

myMenu += '<li class="border-top my-3"></li>';

myMenu += '<li class="mb-1">';
myMenu += '<button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse" data-bs-target="#drive-collapse" aria-expanded="false">Material de apoyo</button>';
myMenu += '<div class="collapse" id="drive-collapse">';
myMenu += '<ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">';
myMenu += '<li><a href="material_de_apoyo.html#tutoriales" class="link-dark rounded">Tutoriales</a></li>';
myMenu += '<li><a href="material_de_apoyo.html#marcadores" class="link-dark rounded">Marcadores</a></li>';
myMenu += '<li><a href="https://drive.google.com/drive/folders/0B1R6zq7kCgNAcW03ajhCQUpnSmM?resourcekey=0-gs5HhVQFzYaZKYItQBcmlg&usp=sharing" target="_blank" class="link-dark rounded">Plantillas Drive <i class="bx bx-exit"></i></a></li>';
myMenu += '<li><a href="https://drive.google.com/drive/folders/1NTtfJJFlc6S6LFbxwE94ay2JyafMUkeG?usp=sharing" target="_blank" class="link-dark rounded">Programas Drive <i class="bx bx-exit"></i></a></li>';
myMenu += '<li><a href="https://drive.google.com/drive/folders/0B1R6zq7kCgNAQU5PUUV0R2hrVDg?resourcekey=0-lB6JlQEoZtPX8F8yy6Ov3g&usp=sharing" target="_blank" class="link-dark rounded">Corel Draw Drive <i class="bx bx-exit"></i></a></li>';
myMenu += '</ul>';
myMenu += '</div>';
myMenu += '</li>';

myMenu += '<li class="border-top my-3"></li>';

myMenu += '<li class="mb-1">';
myMenu += '<button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse" data-bs-target="#github-collapse"naria-expanded="false">Github Pages</button>';
myMenu += '<div class="collapse" id="github-collapse">';
myMenu += '<ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">';
myMenu += '<li><a href="https://bigjack2.github.io/pruebaboostrap5.github.io/" target="_blank" class="link-dark rounded">Demo Bootstrap 5 <i class="bx bx-exit"></i></a></li>';
myMenu += '<li><a href="https://bigjack2.github.io/portafolio_vanegas.github.io/" target="_blank" class="link-dark rounded">Portafolio web <i class="bx bx-exit"></i></a></li>';
myMenu += '</ul>';
myMenu += '</div>';
myMenu += '</li>';
myMenu += '</ul >';

document.getElementById("jsMenu").innerHTML = myMenu;